### ISSUE TITLE
Target-specific message passing

### ISSUE THREAD

**Issue by tansly** [FBDY/bb-vm#27]
### Current behavior

Message passing mechanism is broadcast only: Messages are received by all sprites that implement a message handler for it. This makes it cumbersome to fire events on specific sprites. One has to define different messages to notify different sprites in order to send a message to a specific sprite. This gets out of hand pretty quickly: Message types lose their semantics as they are overloaded with target information.

### Desired behavior

There should be a way of sending a message to a specific target. May it be a new block with a sprite selector, or a block taking a list of sprites to send the message to etc. The latter would most likely require us to start implementing reference mechanism and can be discussed later.

**Comment by tansly** [comment]
WIP in ` msg-targeted` in all repos.

**Comment by tansly** [comment]
I tried to make the block arguments similar to *clone sprite* blocks that also lists the sprites in the scene in a dropdown menu.

However, even though I made it exactly the same as the clone block, it does not seem to work. Try and see the error. Need help.

**Comment by bozbalci** [comment]
@tansly How can I go about reproducing the error?

**Comment by tansly** [comment]
Running `msg-targeted` branches of gui, blocks and vm linked together as usual.
`npm install` in all, `npm link` in vm and blocks, `npm link @bbge/blocks` in vm, `npm link @bbge/vm @bbge/blocks` in gui and `npm start in gui.

Then I get the `oops, something went wrong screen, and the console says
```
TypeError: a is undefined[Learn More] blockly_compressed_vertical.js:1777
```

The error is actually occurs at `@bbge/blocks/core/field_dropdown.js`, in some `fromJson` function there.

**Comment by tansly** [comment]
Kill me. Turns out that a `return` was missing. Moving on...
