### ISSUE TITLE
Add a dictionary data structure

### ISSUE THREAD

**Issue by tansly** [FBDY/bb-vm#50]
Inspired by the discussion at https://github.com/LLK/scratch-vm/issues/1030#issuecomment-379405892.

I will start by tinkering around to see how this can be implemented.

**Comment by tansly** [comment]
First of all, it is clear that this will involve adding support for a new variable type in bb-vm and bb-blocks. It will also probably need some support in bb-parser for project serialization. Fortunately, I'm familiar with this kind of stuff due to my work on named clones (#42), which also involved creating a new variable type.

I'm starting with stuff related to the variable type.

**Comment by bozbalci** [comment]
Good luck

**Comment by tansly** [comment]
ty

**Comment by tansly** [comment]
Looks like there are several options we can go with to implement the underlying structure for dictionaries: https://stackoverflow.com/questions/7196212/how-to-create-dictionary-and-add-key-value-pairs-dynamically
